-- src/main/resources/schema.sql
DROP TABLE IF EXISTS comment;
DROP TABLE IF EXISTS news;
DROP TABLE IF EXISTS category;
DROP TABLE IF EXISTS app_user;

-- Создание таблицы app_user
CREATE TABLE app_user (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          username VARCHAR(255) NOT NULL,
                          password VARCHAR(255) NOT NULL
);

-- Создание таблицы category
CREATE TABLE category (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          name VARCHAR(255) NOT NULL
);

-- Создание таблицы news
CREATE TABLE news (
                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      title VARCHAR(255) NOT NULL,
                      content TEXT NOT NULL,
                      author_id BIGINT NOT NULL,
                      category_id BIGINT NOT NULL,
                      FOREIGN KEY (author_id) REFERENCES app_user (id),
                      FOREIGN KEY (category_id) REFERENCES category(id)
);

-- Создание таблицы comment
CREATE TABLE comment (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         content TEXT NOT NULL,
                         author_id BIGINT NOT NULL,
                         news_id BIGINT NOT NULL,
                         FOREIGN KEY (author_id) REFERENCES app_user (id),
                         FOREIGN KEY (news_id) REFERENCES news(id)
);
